### ISSUE TITLE
Fix hamburger menu

### ISSUE THREAD

**Issue by rezziemaven** [luvi/caricovidsite#15]
I noticed that the hamburger menu currently shows the menu items outside of the menu. Clicking on the button then shows the menu items in the expected place. Here are some screenshots:

![Screen Shot 2020-10-06 at 8 37 19 PM](https://user-images.githubusercontent.com/31511822/95274459-ed166200-0813-11eb-855c-cb29e2136875.png)
_Menu items appear to the right when they should be hidden_

![Screen Shot 2020-10-06 at 8 37 28 PM](https://user-images.githubusercontent.com/31511822/95274469-f3a4d980-0813-11eb-8ae7-e8a89f6e35ec.png)
_Menu items appear below the title when the button is clicked. Menu items could be more distinguishable, perhaps in a lighter grey container_

**Comment by luvi** [comment]
Thank you so much for this!

**Comment by maxrru** [comment]
G'day, I just opened a PR for this issue. Do you mind taking a look @luvi ? :)

**Comment by luvi** [comment]
Hey @maxrru ! I approved it a few days ago I hope you saw. I appreciate it
