### ISSUE TITLE
Add multilingual support

### ISSUE THREAD

**Issue by rezziemaven** [luvi/caricovidsite#20]
I was wondering if you would want to offer other languages so that it would make this site more user-friendly to non-English speaking Caribbean countries eg. Spanish, French, Dutch. I was thinking one easy (and free) way might be using some free translation API to translate the strings, although the strings may not be 100% correct in some cases. Or perhaps we can also ask for user-contributed translations for free. What do you think?

**Comment by luvi** [comment]
this is a great idea! Definitely useful as we are a multilingual region!

**Comment by maxrru** [comment]
Hello! 
I would like to take care of that ticket and at least do the ground work to support localization. I would like to introduce i18next to your project, do you mind taking a look at it and decide whether it would fit your needs?

**Comment by luvi** [comment]
Hi @maxrru , that would be great, I am familiar with i18next and think it would be a great addition, even if you just lay the groundwork.

**Comment by luvi** [comment]
Merged
