### ISSUE TITLE
Sizing

### ISSUE THREAD

**Issue by EugeneGohh** [luvi/caricovidsite#28]
## Suggesting to change the size of the box on smaller screen size

![sizing](https://user-images.githubusercontent.com/64187129/98505707-bad5a580-2294-11eb-9cb8-a29b84f02a6b.png)

**Comment by luvi** [comment]
Thank you for pointing out this issue! Indeed this should be fixed.

**Comment by EugeneGohh** [comment]
May I know where is the css file for it? Seems like I can't find it.

**Comment by luvi** [comment]
Hi Eugene, sorry for the late response. It's all in-line in Map.js. Would definitely be better to extract the styles there to a css file.
