### ISSUE TITLE
Change dismiss to an "x" 

### ISSUE THREAD

**Issue by luvi** [luvi/caricovidsite#5]
The Highest and Lowest Cases Cards can be dismissed so that they do not block the map view on mobile. It would be much more elegant to have a small "x" with no underline, with the same functionality.

<img width="287" alt="Screenshot 2020-08-10 at 10 11 38 PM" src="https://user-images.githubusercontent.com/5286680/89826449-8a2b8600-db56-11ea-90b8-84da15a08212.png">

**Comment by jennybean** [comment]
@luvi I can help you with this once Hacktoberfest starts tomorrow!

**Comment by luvi** [comment]
sure @jennybean! :)

**Comment by Ahkam95** [comment]
@luvi  please check my pull request.
